@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 07 09:43:09 +0200 2024
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim VGA_Module_tb_behav -key {Behavioral:sim_1:Functional:VGA_Module_tb} -tclbatch VGA_Module_tb.tcl -view F:/My_sem_10/sem10_my_material/MICRO_LAB/labs/vga_controller_copy/vga_controller_copy.sim/VGA_Module_tb_behav.wcfg -log simulate.log"
call xsim  VGA_Module_tb_behav -key {Behavioral:sim_1:Functional:VGA_Module_tb} -tclbatch VGA_Module_tb.tcl -view F:/My_sem_10/sem10_my_material/MICRO_LAB/labs/vga_controller_copy/vga_controller_copy.sim/VGA_Module_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
