// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mult,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.470000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=13,HLS_VERSION=2020_1}" *)

module mult (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_V,
        B_V,
        result_V,
        result_V_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] A_V;
input  [3:0] B_V;
output  [7:0] result_V;
output   result_V_ap_vld;

reg result_V_ap_vld;

wire   [3:0] ret_V_fu_43_p0;
wire   [3:0] ret_V_fu_43_p1;
wire   [7:0] ret_V_fu_43_p00;
wire   [7:0] ret_V_fu_43_p10;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        result_V_ap_vld = 1'b1;
    end else begin
        result_V_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign result_V = (ret_V_fu_43_p0 * ret_V_fu_43_p1);

assign ret_V_fu_43_p0 = ret_V_fu_43_p00;

assign ret_V_fu_43_p00 = B_V;

assign ret_V_fu_43_p1 = ret_V_fu_43_p10;

assign ret_V_fu_43_p10 = A_V;

endmodule //mult
