// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "add.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic add::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic add::ap_const_logic_0 = sc_dt::Log_0;
const bool add::ap_const_boolean_1 = true;

add::add(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_lhs_V_fu_35_p1);
    sensitive << ( A_V );

    SC_METHOD(thread_out_V);
    sensitive << ( ap_start );
    sensitive << ( rhs_V_fu_39_p1 );
    sensitive << ( lhs_V_fu_35_p1 );

    SC_METHOD(thread_out_V_ap_vld);
    sensitive << ( ap_start );

    SC_METHOD(thread_rhs_V_fu_39_p1);
    sensitive << ( B_V );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "add_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_V, "(port)A_V");
    sc_trace(mVcdFile, B_V, "(port)B_V");
    sc_trace(mVcdFile, out_V, "(port)out_V");
    sc_trace(mVcdFile, out_V_ap_vld, "(port)out_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, rhs_V_fu_39_p1, "rhs_V_fu_39_p1");
    sc_trace(mVcdFile, lhs_V_fu_35_p1, "lhs_V_fu_35_p1");
#endif

    }
    mHdltvinHandle.open("add.hdltvin.dat");
    mHdltvoutHandle.open("add.hdltvout.dat");
}

add::~add() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void add::thread_ap_done() {
    ap_done = ap_start.read();
}

void add::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void add::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void add::thread_lhs_V_fu_35_p1() {
    lhs_V_fu_35_p1 = esl_zext<5,4>(A_V.read());
}

void add::thread_out_V() {
    out_V = (!rhs_V_fu_39_p1.read().is_01() || !lhs_V_fu_35_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(rhs_V_fu_39_p1.read()) + sc_biguint<5>(lhs_V_fu_35_p1.read()));
}

void add::thread_out_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) {
        out_V_ap_vld = ap_const_logic_1;
    } else {
        out_V_ap_vld = ap_const_logic_0;
    }
}

void add::thread_rhs_V_fu_39_p1() {
    rhs_V_fu_39_p1 = esl_zext<5,4>(B_V.read());
}

void add::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_V\" :  \"" << A_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_V\" :  \"" << B_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_V\" :  \"" << out_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_V_ap_vld\" :  \"" << out_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

