// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "divide.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic divide::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic divide::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> divide::ap_ST_fsm_state1 = "1";
const sc_lv<8> divide::ap_ST_fsm_state2 = "10";
const sc_lv<8> divide::ap_ST_fsm_state3 = "100";
const sc_lv<8> divide::ap_ST_fsm_state4 = "1000";
const sc_lv<8> divide::ap_ST_fsm_state5 = "10000";
const sc_lv<8> divide::ap_ST_fsm_state6 = "100000";
const sc_lv<8> divide::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> divide::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> divide::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> divide::ap_const_lv32_7 = "111";
const bool divide::ap_const_boolean_1 = true;

divide::divide(sc_module_name name) : sc_module(name), mVcdFile(0) {
    divide_udiv_4ns_4bkb_U1 = new divide_udiv_4ns_4bkb<1,8,4,4,4>("divide_udiv_4ns_4bkb_U1");
    divide_udiv_4ns_4bkb_U1->clk(ap_clk);
    divide_udiv_4ns_4bkb_U1->reset(ap_rst);
    divide_udiv_4ns_4bkb_U1->start(grp_fu_35_ap_start);
    divide_udiv_4ns_4bkb_U1->done(grp_fu_35_ap_done);
    divide_udiv_4ns_4bkb_U1->din0(A_V);
    divide_udiv_4ns_4bkb_U1->din1(B_V);
    divide_udiv_4ns_4bkb_U1->ce(ap_var_for_const0);
    divide_udiv_4ns_4bkb_U1->dout(grp_fu_35_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_35_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_result_V);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_fu_35_p2 );

    SC_METHOD(thread_result_V_ap_vld);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "divide_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_V, "(port)A_V");
    sc_trace(mVcdFile, B_V, "(port)B_V");
    sc_trace(mVcdFile, result_V, "(port)result_V");
    sc_trace(mVcdFile, result_V_ap_vld, "(port)result_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_35_p2, "grp_fu_35_p2");
    sc_trace(mVcdFile, grp_fu_35_ap_start, "grp_fu_35_ap_start");
    sc_trace(mVcdFile, grp_fu_35_ap_done, "grp_fu_35_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("divide.hdltvin.dat");
    mHdltvoutHandle.open("divide.hdltvout.dat");
}

divide::~divide() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete divide_udiv_4ns_4bkb_U1;
}

void divide::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void divide::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void divide::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void divide::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void divide::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void divide::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void divide::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void divide::thread_grp_fu_35_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        grp_fu_35_ap_start = ap_const_logic_1;
    } else {
        grp_fu_35_ap_start = ap_const_logic_0;
    }
}

void divide::thread_result_V() {
    result_V = esl_zext<8,4>(grp_fu_35_p2.read());
}

void divide::thread_result_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        result_V_ap_vld = ap_const_logic_1;
    } else {
        result_V_ap_vld = ap_const_logic_0;
    }
}

void divide::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

void divide::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_V\" :  \"" << A_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_V\" :  \"" << B_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_V\" :  \"" << result_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_V_ap_vld\" :  \"" << result_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

