// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="add,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.362000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=15,HLS_VERSION=2020_1}" *)

module add (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_V,
        B_V,
        out_V,
        out_V_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] A_V;
input  [3:0] B_V;
output  [4:0] out_V;
output   out_V_ap_vld;

reg out_V_ap_vld;

wire   [4:0] rhs_V_fu_39_p1;
wire   [4:0] lhs_V_fu_35_p1;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        out_V_ap_vld = 1'b1;
    end else begin
        out_V_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign lhs_V_fu_35_p1 = A_V;

assign out_V = (rhs_V_fu_39_p1 + lhs_V_fu_35_p1);

assign rhs_V_fu_39_p1 = B_V;

endmodule //add
