// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mult_HH_
#define _mult_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct mult : public sc_module {
    // Port declarations 8
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<4> > A_V;
    sc_in< sc_lv<4> > B_V;
    sc_out< sc_lv<8> > result_V;
    sc_out< sc_logic > result_V_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    mult(sc_module_name name);
    SC_HAS_PROCESS(mult);

    ~mult();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<4> > ret_V_fu_43_p0;
    sc_signal< sc_lv<4> > ret_V_fu_43_p1;
    sc_signal< sc_lv<8> > ret_V_fu_43_p00;
    sc_signal< sc_lv<8> > ret_V_fu_43_p10;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_result_V();
    void thread_result_V_ap_vld();
    void thread_ret_V_fu_43_p0();
    void thread_ret_V_fu_43_p00();
    void thread_ret_V_fu_43_p1();
    void thread_ret_V_fu_43_p10();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
