// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic mult::ap_const_logic_1 = sc_dt::Log_1;
const bool mult::ap_const_boolean_1 = true;
const sc_logic mult::ap_const_logic_0 = sc_dt::Log_0;

mult::mult(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_result_V);
    sensitive << ( ap_start );
    sensitive << ( ret_V_fu_43_p0 );
    sensitive << ( ret_V_fu_43_p1 );

    SC_METHOD(thread_result_V_ap_vld);
    sensitive << ( ap_start );

    SC_METHOD(thread_ret_V_fu_43_p0);
    sensitive << ( ret_V_fu_43_p00 );

    SC_METHOD(thread_ret_V_fu_43_p00);
    sensitive << ( B_V );

    SC_METHOD(thread_ret_V_fu_43_p1);
    sensitive << ( ret_V_fu_43_p10 );

    SC_METHOD(thread_ret_V_fu_43_p10);
    sensitive << ( A_V );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_V, "(port)A_V");
    sc_trace(mVcdFile, B_V, "(port)B_V");
    sc_trace(mVcdFile, result_V, "(port)result_V");
    sc_trace(mVcdFile, result_V_ap_vld, "(port)result_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ret_V_fu_43_p0, "ret_V_fu_43_p0");
    sc_trace(mVcdFile, ret_V_fu_43_p1, "ret_V_fu_43_p1");
    sc_trace(mVcdFile, ret_V_fu_43_p00, "ret_V_fu_43_p00");
    sc_trace(mVcdFile, ret_V_fu_43_p10, "ret_V_fu_43_p10");
#endif

    }
    mHdltvinHandle.open("mult.hdltvin.dat");
    mHdltvoutHandle.open("mult.hdltvout.dat");
}

mult::~mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void mult::thread_ap_done() {
    ap_done = ap_start.read();
}

void mult::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void mult::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void mult::thread_result_V() {
    result_V = (!ret_V_fu_43_p0.read().is_01() || !ret_V_fu_43_p1.read().is_01())? sc_lv<8>(): sc_biguint<4>(ret_V_fu_43_p0.read()) * sc_biguint<4>(ret_V_fu_43_p1.read());
}

void mult::thread_result_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) {
        result_V_ap_vld = ap_const_logic_1;
    } else {
        result_V_ap_vld = ap_const_logic_0;
    }
}

void mult::thread_ret_V_fu_43_p0() {
    ret_V_fu_43_p0 =  (sc_lv<4>) (ret_V_fu_43_p00.read());
}

void mult::thread_ret_V_fu_43_p00() {
    ret_V_fu_43_p00 = esl_zext<8,4>(B_V.read());
}

void mult::thread_ret_V_fu_43_p1() {
    ret_V_fu_43_p1 =  (sc_lv<4>) (ret_V_fu_43_p10.read());
}

void mult::thread_ret_V_fu_43_p10() {
    ret_V_fu_43_p10 = esl_zext<8,4>(A_V.read());
}

void mult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_V\" :  \"" << A_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_V\" :  \"" << B_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_V\" :  \"" << result_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_V_ap_vld\" :  \"" << result_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

